pub const DEFAULT_PROGRESS_INTERVAL_SECONDS: u64 = 30;
pub const VERBOSE_PROGRESS_INTERVAL_SECONDS: u64 = 5;
pub const BYTES_PER_GB: f64 = 1_073_741_824.0;

pub const DEFAULT_SAMPLE_SIZE: usize = 100;
pub const DEFAULT_RECORD_ESTIMATED_BYTES: usize = 200;
pub const DEFAULT_MAX_GPU_BATCH_SIZE: usize = 100000;
pub const DEFAULT_CPU_SEGMENT_MIN_MB: usize = 64;
pub const DEFAULT_MAX_URL_LENGTH_FOR_FAST_NORMALIZATION: usize = 512;
