pub const DEFAULT_PROGRESS_INTERVAL_SECONDS: u64 = 30;
pub const VERBOSE_PROGRESS_INTERVAL_SECONDS: u64 = 5;
pub const BYTES_PER_GB: f64 = 1_073_741_824.0;

pub const DEFAULT_SAMPLE_SIZE: usize = 100;
pub const DEFAULT_RECORD_ESTIMATED_BYTES: usize = 200;
pub const DEFAULT_MIN_GPU_BATCH_SIZE: usize = 1024;
pub const DEFAULT_MAX_GPU_BATCH_SIZE: usize = 100000;
pub const DEFAULT_GPU_SEGMENT_BASE_SIZE_MB: usize = 128;
pub const DEFAULT_GPU_MEMORY_USAGE_PERCENT: f64 = 0.2;
pub const DEFAULT_GPU_BUS_WIDTH_NORMALIZATION: f64 = 256.0;
pub const DEFAULT_GPU_L2_CACHE_NORMALIZATION_MB: f64 = 2.0;
pub const DEFAULT_GPU_COMPUTE_CAPABILITY_FACTOR: f64 = 2.0;
pub const DEFAULT_GPU_THREADS_PER_BLOCK_DIVISOR: usize = 32;
pub const DEFAULT_CPU_SEGMENT_MIN_MB: usize = 64;
pub const DEFAULT_MAX_URL_LENGTH_FOR_FAST_NORMALIZATION: usize = 512;
